import {useEffect,useState} from 'react';
import {Search,ShoppingCart,Store,User,Package,LogIn,LogOut,Plus,Minus,X,ChevronRight} from 'lucide-react';
type Shop={id:number;name:string;slug:string;description:string;created_at:string};
type Product={id:number;name:string;description:string;price:number;stock:number;is_active:boolean;created_at:string};
type CartItem={product:Product;quantity:number};
const API='/api';
async function api<T>(path:string,o:RequestInit={}){const h=new Headers(o.headers);h.set('Accept','application/json');if(o.body&&typeof o.body==='string')h.set('Content-Type','application/json');const token=localStorage.getItem('mm_token');if(token)h.set('Authorization','Bearer '+token);const r=await fetch(API+path,{...o,headers:h});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||'Wystąpił błąd');return r.json() as Promise<T>}
const money=(v:number)=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN'}).format(v);
export default function App(){
 const[shops,setShops]=useState<Shop[]>([]),[products,setProducts]=useState<Product[]>([]),[selected,setSelected]=useState<Shop|null>(null),[cart,setCart]=useState<CartItem[]>([]),[query,setQuery]=useState(''),[view,setView]=useState('home'),[modal,setModal]=useState(''),[product,setProduct]=useState<Product|null>(null),[user,setUser]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[error,setError]=useState('');
 useEffect(()=>{api<Shop[]>('/shops/').then(setShops).catch(e=>setError(e.message));const u=localStorage.getItem('mm_user');if(u)setUser(JSON.parse(u));const c=localStorage.getItem('mm_cart');if(c)setCart(JSON.parse(c))},[]);
 useEffect(()=>localStorage.setItem('mm_cart',JSON.stringify(cart)),[cart]);
 const filtered=products.filter(p=>p.is_active&&(p.name+' '+p.description).toLowerCase().includes(query.toLowerCase()));
 const count=cart.reduce((a,x)=>a+x.quantity,0),total=cart.reduce((a,x)=>a+x.quantity*x.product.price,0);
 async function openShop(s:Shop){setSelected(s);setProducts(await api<Product[]>('/products/shop/'+s.id))}
 function add(p:Product){setCart(c=>{const x=c.find(i=>i.product.id===p.id);return x?c.map(i=>i.product.id===p.id?{...i,quantity:Math.min(i.quantity+1,p.stock)}:i):[...c,{product:p,quantity:1}]})}
 function qty(id:number,d:number){setCart(c=>c.map(i=>i.product.id===id?{...i,quantity:i.quantity+d}:i).filter(i=>i.quantity>0))}
 async function doLogin(e:React.FormEvent){e.preventDefault();const f=e.currentTarget as HTMLFormElement;const fd=new FormData(f);const body=new URLSearchParams();body.set('username',String(fd.get('email')));body.set('password',String(fd.get('password')));try{const t=await api<any>('/users/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});localStorage.setItem('mm_token',t.access_token);const u={email:fd.get('email')};localStorage.setItem('mm_user',JSON.stringify(u));setUser(u);setModal('')}catch(e:any){setError(e.message)}}
 async function doRegister(e:React.FormEvent){e.preventDefault();const f=e.currentTarget as HTMLFormElement;const fd=new FormData(f);try{const u=await api<any>('/users/register',{method:'POST',body:JSON.stringify({email:fd.get('email'),password:fd.get('password'),full_name:fd.get('full_name')})});localStorage.setItem('mm_user',JSON.stringify(u));setUser(u);setModal('')}catch(e:any){setError(e.message)}}
 async function checkout(){try{await api('/orders/create',{method:'POST',body:JSON.stringify({items:cart.map(x=>({product_id:x.product.id,quantity:x.quantity}))})});setCart([]);setModal('');setView('orders')}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(view==='orders'&&user)api<any[]>('/orders/user/me').then(setOrders).catch(()=>{})},[view,user]);
 return <div><header><div className="nav"><button className="brand" onClick={()=>setView('home')}><i>m</i>mini<span>Market</span></button><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Szukaj produktów..."/></div><nav><button onClick={()=>setView('home')}>Sklepy</button>{user&&<button onClick={()=>setView('orders')}>Zamówienia</button>}<button onClick={()=>setView('account')}><User size={18}/></button><button onClick={()=>setModal('cart')} className="cart"><ShoppingCart size={18}/><b>{count}</b></button></nav></div></header>
 {error&&<div className="toast">{error}<button onClick={()=>setError('')}><X size={15}/></button></div>}
 {view==='home'&&<main>{!selected?<><section className="hero"><div><small>PROSTE ZAKUPY ONLINE</small><h1>Twój lokalny<br/><em>market.</em></h1><p>Odkrywaj produkty od niezależnych sprzedawców i zamawiaj bez zbędnych kroków.</p></div><div className="heroCard"><Store/><strong>{shops.length}</strong><span>aktywnych sklepów</span></div></section><section className="section"><small>ODKRYWAJ</small><h2>Sklepy</h2><div className="shopGrid">{shops.map(s=><button className="shopCard" key={s.id} onClick={()=>openShop(s)}><div className="shopIcon"><Store/></div><div><h3>{s.name}</h3><p>{s.description||'Lokalny sklep'}</p><span>Przeglądaj produkty <ChevronRight size={14}/></span></div></button>)}</div></section></>:<section className="section"><button className="back" onClick={()=>setSelected(null)}>← Wszystkie sklepy</button><h2>{selected.name}</h2><p>{selected.description}</p><div className="productGrid">{filtered.map(p=><article className="product" key={p.id}><div className="productVisual"><Package size={38}/></div><div className="productBody"><small>DOSTĘPNY</small><h3>{p.name}</h3><p>{p.description}</p><div className="price"><strong>{money(p.price)}</strong><button onClick={()=>add(p)} disabled={!p.stock}><Plus size={17}/></button></div></div><button className="whole" onClick={()=>{setProduct(p);setModal('product')}}/></article>)}</div></section>}</main>}
 {view==='orders'&&<section className="section narrow"><small>TWOJE ZAKUPY</small><h2>Zamówienia</h2>{orders.map(o=><article className="order" key={o.id}><div><small>#{String(o.id).slice(0,8)}</small><h3>{o.items.length} produktów</h3></div><b>{money(o.total)}</b></article>)}{!orders.length&&<div className="empty"><h3>Nie masz jeszcze zamówień</h3><button className="primary" onClick={()=>setView('home')}>Przeglądaj sklepy</button></div>}</section>}
 {view==='account'&&<section className="section narrow"><small>KONTO</small><h2>Twoje konto</h2><div className="account"><div className="avatar"><User/></div>{user?<><h3>{user.full_name||user.email}</h3><p>{user.email}</p><button className="secondary" onClick={()=>{localStorage.removeItem('mm_token');localStorage.removeItem('mm_user');setUser(null)}}><LogOut size={16}/> Wyloguj</button></>:<><h3>Zaloguj się, aby korzystać z konta</h3><button className="primary" onClick={()=>setModal('login')}>Zaloguj się</button></>}</div></section>}
 <footer>© 2026 miniMarket <span>Marketplace dla lokalnych sprzedawców</span></footer>
 {modal==='login'&&<Modal title="Witaj ponownie" close={()=>setModal('')}><form onSubmit={doLogin}><Field n="email" t="E-mail" type="email"/><Field n="password" t="Hasło" type="password"/><button className="primary full"><LogIn size={16}/> Zaloguj się</button><button type="button" className="link" onClick={()=>setModal('register')}>Nie masz konta? Zarejestruj się</button></form></Modal>}
 {modal==='register'&&<Modal title="Utwórz konto" close={()=>setModal('')}><form onSubmit={doRegister}><Field n="full_name" t="Imię i nazwisko"/><Field n="email" t="E-mail" type="email"/><Field n="password" t="Hasło" type="password"/><button className="primary full">Utwórz konto</button><button type="button" className="link" onClick={()=>setModal('login')}>Masz już konto? Zaloguj się</button></form></Modal>}
 {modal==='product'&&product&&<Modal title={product.name} close={()=>setModal('')}><div className="productVisual big"><Package size={55}/></div><p>{product.description}</p><strong className="modalPrice">{money(product.price)}</strong><button className="primary full" onClick={()=>{add(product);setModal('')}}>Dodaj do koszyka</button></Modal>}
 {modal==='cart'&&<Modal title="Twój koszyk" close={()=>setModal('')}>{cart.length?<><div>{cart.map(i=><div className="cartItem" key={i.product.id}><div><b>{i.product.name}</b><span>{money(i.product.price)} / szt.</span></div><div className="qty"><button onClick={()=>qty(i.product.id,-1)}><Minus size={13}/></button>{i.quantity}<button onClick={()=>qty(i.product.id,1)}><Plus size={13}/></button></div></div>)}</div><div className="total">Razem <strong>{money(total)}</strong></div><button className="primary full" onClick={user?checkout:()=>setModal('login')}>{user?'Złóż zamówienie':'Zaloguj się, aby zamówić'}</button></>:<div className="empty">Koszyk jest pusty.</div>}</Modal>}
 </div>
}
function Field({n,t,type='text'}:{n:string;t:string;type?:string}){return <label className="field"><span>{t}</span><input name={n} type={type} required/></label>}
function Modal({title,close,children}:{title:string;close:()=>void;children:any}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modalHead"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}